// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package minitec_db

import (
	"database/sql"
)

type Project struct {
	ID   int64
	Name string
	Code string
}

type State struct {
	ID         int64
	FinalState int32
	StartDate  sql.NullTime
	EndDate    sql.NullTime
	StationID  int64
}

type Station struct {
	ID        int64
	Name      string
	ProjectID int64
}

type User struct {
	ID         int64
	FirstName  string
	SecondName string
	Email      string
	Isadmin    bool
	Isbanned   bool
}

type UserProject struct {
	ID        int64
	UserID    int64
	ProjectID int64
}
